version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=marketplace_user
      - DATABASE_PASSWORD=marketplace_pass
      - DATABASE_NAME=marketplace_db
      - JWT_SECRET=your-super-secret-jwt-key-here-change-in-production
      - JWT_EXPIRES_IN=24h
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=your-email@gmail.com
      - SMTP_PASS=your-app-password
    depends_on:
      - postgres
      - redis
    volumes:
      - ./uploads:/app/uploads
    networks:
      - marketplace-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=marketplace_db
      - POSTGRES_USER=marketplace_user
      - POSTGRES_PASSWORD=marketplace_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - marketplace-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - marketplace-network

  # Optional: Redis Commander for Redis management
  redis-commander:
    image: rediscommander/redis-commander:latest
    hostname: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
      - marketplace-network
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data:

networks:
  marketplace-network:
    driver: bridge